-- error.lua
print(a+1)